"""Exact structural grammar for archives generated by :mod:`ghravioli.archive`."""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from uuid import UUID

from ghravioli.constants import (
    COMPONENT_CENTRE_BAND,
    COMPONENT_EDGE_PADDING,
    LABEL_CHARACTER_WIDTH,
    LABEL_PADDING,
    MAX_COLUMN_WIDTH,
    MIN_INPUT_WIDTH,
    MIN_OUTPUT_WIDTH,
    MIN_PANEL_HEIGHT,
    NARROW_SLIDER_DIGITS,
    NARROW_SLIDER_RANGE,
    PANEL_WIDTH,
    PARAMETER_ROW_HEIGHT,
    SLIDER_DIGITS,
    SLIDER_WIDTH,
    TOGGLE_WIDTH,
)
from ghravioli.display import contains_unsafe_terminal_text
from ghravioli.manifest import MAX_DESCRIPTION_LENGTH, MAX_NAME_LENGTH


class ArchiveSchemaError(ValueError):
    """Archive XML falls outside ghRavioli's generated structural subset."""


_ANY = object()


@dataclass(frozen=True)
class _ItemRule:
    name: str
    type_name: str
    type_code: str
    value: object = _ANY
    index: int | None = None
    children: tuple[tuple[str, object], ...] = ()
    max_length: int | None = None
    allow_empty: bool = True
    trimmed: bool = False


def validate_generated_archive_schema(root: ET.Element) -> None:
    """Reject every element, attribute, item, and chunk not emitted by the builder."""

    _expect_attributes(root, {"name": "Root"}, "Archive")
    _expect_items(
        root,
        (
            _ItemRule(
                "ArchiveVersion",
                "gh_version",
                "80",
                children=(("Major", "0"), ("Minor", "2"), ("Revision", "2")),
            ),
        ),
        "Archive",
        has_chunks=True,
    )
    clipboard = _expect_chunks(root, (("Clipboard", None),), "Archive")[0]
    _validate_clipboard(clipboard)


def _validate_clipboard(clipboard: ET.Element) -> None:
    _expect_items(
        clipboard,
        (
            _ItemRule(
                "plugin_version",
                "gh_version",
                "80",
                children=(("Major", "1"), ("Minor", "0"), ("Revision", "8")),
            ),
        ),
        "Clipboard",
        has_chunks=True,
    )
    chunks = _expect_chunks(
        clipboard,
        (
            ("DocumentHeader", None),
            ("DefinitionProperties", None),
            ("RcpLayout", None),
            ("GHALibraries", None),
            ("DefinitionObjects", None),
        ),
        "Clipboard",
    )
    _validate_document_header(chunks[0])
    _validate_definition_properties(chunks[1])
    _validate_rcp_layout(chunks[2])
    _validate_libraries(chunks[3])
    _validate_definition_objects(chunks[4])


def _validate_document_header(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule("DocumentID", "gh_guid", "9"),
            _ItemRule("Preview", "gh_string", "10", "Shaded"),
            _ItemRule("PreviewMeshType", "gh_int32", "3", "1"),
            _ItemRule(
                "PreviewNormal",
                "gh_drawing_color",
                "36",
                children=(("ARGB", "100;150;0;0"),),
            ),
            _ItemRule(
                "PreviewSelected",
                "gh_drawing_color",
                "36",
                children=(("ARGB", "100;0;150;0"),),
            ),
        ),
        "DocumentHeader",
    )


def _validate_definition_properties(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule("Date", "gh_date", "8", "0"),
            _ItemRule("Description", "gh_string", "10", ""),
            _ItemRule("KeepOpen", "gh_bool", "1", "false"),
            _ItemRule(
                "Name",
                "gh_string",
                "10",
                max_length=MAX_NAME_LENGTH,
                allow_empty=False,
                trimmed=True,
            ),
        ),
        "DefinitionProperties",
        has_chunks=True,
    )
    revisions, projection, views = _expect_chunks(
        chunk,
        (("Revisions", None), ("Projection", None), ("Views", None)),
        "DefinitionProperties",
    )
    _expect_items(
        revisions,
        (_ItemRule("RevisionCount", "gh_int32", "3", "0"),),
        "Revisions",
    )
    _expect_items(
        projection,
        (
            _ItemRule(
                "Target",
                "gh_drawing_point",
                "30",
                children=(("X", "0"), ("Y", "0")),
            ),
            _ItemRule("Zoom", "gh_single", "5", "1"),
        ),
        "Projection",
    )
    _expect_items(
        views,
        (_ItemRule("ViewCount", "gh_int32", "3", "0"),),
        "Views",
    )


def _validate_rcp_layout(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (_ItemRule("GroupCount", "gh_int32", "3", "0"),),
        "RcpLayout",
    )


def _validate_libraries(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (_ItemRule("Count", "gh_int32", "3", "1"),),
        "GHALibraries",
        has_chunks=True,
    )
    library = _expect_chunks(chunk, (("Library", 0),), "GHALibraries")[0]
    _expect_items(
        library,
        (
            _ItemRule("Author", "gh_string", "10", "Robert McNeel & Associates"),
            _ItemRule("Id", "gh_guid", "9", "00000000-0000-0000-0000-000000000000"),
            _ItemRule("Name", "gh_string", "10", "Grasshopper"),
            _ItemRule("Version", "gh_string", "10", "8.0"),
        ),
        "Library",
    )


def _validate_definition_objects(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (_ItemRule("ObjectCount", "gh_int32", "3"),),
        "DefinitionObjects",
        has_chunks=True,
    )
    objects = _chunk_elements(chunk, "DefinitionObjects")
    unexpected = next((item for item in objects if item.get("name") != "Object"), None)
    if unexpected is not None:
        raise ArchiveSchemaError(
            "DefinitionObjects has unexpected chunk "
            f"{unexpected.get('name')!r} outside the generated schema"
        )
    expected = tuple(("Object", index) for index in range(len(objects)))
    for object_chunk in _expect_chunks(chunk, expected, "DefinitionObjects"):
        _validate_object(object_chunk)


COMPANION_OBJECT_NAMES = ("Panel", "Boolean Toggle", "Number Slider")


def _object_name(chunk: ET.Element) -> str:
    """Return the declared object name, or reject anything unrecognised."""

    items = chunk.find("./items")
    if items is None:
        raise ArchiveSchemaError("Object is missing canonical items")
    for item in items:
        if item.get("name") == "Name":
            return item.text or ""
    raise ArchiveSchemaError("Object is missing Name")


def _validate_object(chunk: ET.Element) -> None:
    name = _object_name(chunk)
    allowed = ("Python 3 Script",) + COMPANION_OBJECT_NAMES
    if name not in allowed:
        raise ArchiveSchemaError(
            f"Object {name!r} is outside the generated schema"
        )
    _expect_items(
        chunk,
        (
            _ItemRule("GUID", "gh_guid", "9"),
            _ItemRule("Name", "gh_string", "10", name),
        ),
        "Object",
        has_chunks=True,
    )
    container = _expect_chunks(chunk, (("Container", None),), "Object")[0]
    if name == "Python 3 Script":
        _validate_container(container)
    elif name == "Panel":
        _validate_panel_container(container)
    else:
        _validate_widget_container(container, name)


def _companion_identity_rules(
    name: str,
    *,
    description: object = _ANY,
    nickname: object = _ANY,
) -> tuple[_ItemRule, ...]:
    """Return the identity items every companion container shares."""

    return (
        _ItemRule(
            "Description",
            "gh_string",
            "10",
            description,
            max_length=MAX_DESCRIPTION_LENGTH,
            trimmed=True,
        ),
        _ItemRule("InstanceGuid", "gh_guid", "9"),
        _ItemRule("Name", "gh_string", "10", name),
        _ItemRule(
            "NickName",
            "gh_string",
            "10",
            nickname,
            max_length=MAX_NAME_LENGTH,
            trimmed=True,
        ),
        _ItemRule("Optional", "gh_bool", "1", "false"),
    )


def _validate_panel_container(chunk: ET.Element) -> None:
    items = _item_elements(chunk, "Panel Container", has_chunks=True)
    allowed = {
        "Description",
        "InstanceGuid",
        "Name",
        "NickName",
        "Optional",
        "Source",
        "SourceCount",
        "UserText",
    }
    _reject_unexpected_item_names(items, allowed, "Panel Container")
    rules = (
        # A panel's nickname and description are the output port's own, so
        # they cannot be pinned to a literal here. Inspection cross-references
        # them against that port instead, which is the stronger check.
        *_companion_identity_rules("Panel"),
        *_source_rules(items, "Panel Container", required=1),
        _ItemRule(
            "UserText",
            "gh_string",
            "10",
            "",
            max_length=MAX_DESCRIPTION_LENGTH,
        ),
    )
    _validate_item_rules(items, rules, "Panel Container")
    attributes, properties = _expect_chunks(
        chunk,
        (("Attributes", None), ("Properties", None)),
        "Panel Container",
    )
    _validate_attributes(
        attributes,
        expected_width=format(PANEL_WIDTH, ".15g"),
        minimum_height=MIN_PANEL_HEIGHT,
        context="Panel",
    )
    _expect_items(
        properties,
        (
            _ItemRule("Alignment", "gh_int32", "3", "0"),
            _ItemRule("DrawIndices", "gh_bool", "1", "false"),
            _ItemRule("DrawPaths", "gh_bool", "1", "false"),
            _ItemRule("Multiline", "gh_bool", "1", "true"),
            _ItemRule("Wrap", "gh_bool", "1", "false"),
        ),
        "Panel Properties",
    )


def _validate_widget_container(chunk: ET.Element, name: str) -> None:
    context = f"{name} Container"
    items = _item_elements(chunk, context, has_chunks=True)
    is_toggle = name == "Boolean Toggle"
    rules = (
        *_companion_identity_rules(name),
        _ItemRule("SourceCount", "gh_int32", "3", "0"),
        *((_ItemRule("Boolean", "gh_bool", "1"),) if is_toggle else ()),
    )
    _reject_unexpected_item_names(items, {rule.name for rule in rules}, context)
    _validate_item_rules(items, rules, context)
    # A widget drives a component; nothing may drive a widget.
    if items and any(item.get("name") == "Source" for item in items):
        raise ArchiveSchemaError(f"{context} must not declare a source connection")
    expected = (("Attributes", None),) + ((() if is_toggle else (("Slider", None),)))
    ordered = _expect_chunks(chunk, expected, context)
    expected_width = TOGGLE_WIDTH if is_toggle else SLIDER_WIDTH
    _validate_attributes(
        ordered[0],
        expected_width=format(expected_width, ".15g"),
        expected_height=format(PARAMETER_ROW_HEIGHT, ".15g"),
    )
    if not is_toggle:
        _validate_slider(ordered[1])


def _validate_slider(chunk: ET.Element) -> None:
    items = _expect_items(
        chunk,
        (
            _ItemRule("GripDisplay", "gh_int32", "3", "0"),
            _ItemRule("Interval", "gh_int32", "3"),
            _ItemRule("Max", "gh_decimal", "7"),
            _ItemRule("Min", "gh_decimal", "7"),
            _ItemRule("Digits", "gh_int32", "3"),
            _ItemRule("Value", "gh_decimal", "7"),
        ),
        "Slider",
    )
    values = {item.get("name"): item.text or "" for item in items}
    if values["Interval"] not in {"0", "1"}:
        raise ArchiveSchemaError("Slider Interval must be 0 or 1")
    for name in ("Max", "Min", "Value"):
        _validate_canonical_number(values[name], f"Slider {name}")
    minimum = float(values["Min"])
    maximum = float(values["Max"])
    value = float(values["Value"])
    if minimum >= maximum:
        raise ArchiveSchemaError("Slider Max must be greater than Min")
    if not minimum <= value <= maximum:
        raise ArchiveSchemaError("Slider Value must fall between Min and Max")
    expected_digits = (
        NARROW_SLIDER_DIGITS
        if maximum - minimum < NARROW_SLIDER_RANGE
        else SLIDER_DIGITS
    )
    if values["Digits"] != str(expected_digits):
        raise ArchiveSchemaError("Slider Digits do not match the generated range")


def _source_rules(
    items: list[ET.Element],
    context: str,
    *,
    required: int | None = None,
) -> tuple[_ItemRule, ...]:
    """Return the SourceCount and Source rules matching declared wiring.

    Wiring is the one place a generated archive may reference another object,
    so the count and the referenced identities must agree exactly rather than
    being accepted on trust.
    """

    sources = [item for item in items if item.get("name") == "Source"]
    count_item = next((item for item in items if item.get("name") == "SourceCount"), None)
    if count_item is None:
        raise ArchiveSchemaError(f"{context} is missing SourceCount")
    declared = count_item.text or ""
    if declared != str(len(sources)):
        raise ArchiveSchemaError(
            f"{context} SourceCount does not match its Source items"
        )
    if len(sources) > 1:
        raise ArchiveSchemaError(
            f"{context} must declare at most one Source; found {len(sources)}"
        )
    if required is not None and len(sources) != required:
        raise ArchiveSchemaError(
            f"{context} Source must appear exactly {required} time"
        )
    return (
        _ItemRule("SourceCount", "gh_int32", "3"),
        *(_ItemRule("Source", "gh_guid", "9", index=index) for index in range(len(sources))),
    )


def _validate_container(chunk: ET.Element) -> None:
    items = _expect_items(
        chunk,
        (
            _ItemRule(
                "Description",
                "gh_string",
                "10",
                max_length=MAX_DESCRIPTION_LENGTH,
                trimmed=True,
            ),
            _ItemRule("GraftStandardOutputLines", "gh_bool", "1", "true"),
            _ItemRule("InstanceGuid", "gh_guid", "9"),
            _ItemRule("MarshGuids", "gh_bool", "1", "true"),
            _ItemRule("MarshInputs", "gh_bool", "1", "true"),
            _ItemRule("MarshOutputs", "gh_bool", "1", "true"),
            _ItemRule("Name", "gh_string", "10", "Python 3 Script"),
            _ItemRule(
                "NickName",
                "gh_string",
                "10",
                max_length=MAX_NAME_LENGTH,
                allow_empty=False,
                trimmed=True,
            ),
            _ItemRule("ScriptComponentVersion", "gh_int32", "3", "3"),
            _ItemRule(
                "Tooltip",
                "gh_string",
                "10",
                max_length=MAX_DESCRIPTION_LENGTH,
                trimmed=True,
            ),
            _ItemRule("UsingLibraryInputParam", "gh_bool", "1", "false"),
            _ItemRule("UsingScriptInputParam", "gh_bool", "1", "false"),
            _ItemRule("UsingScriptOutputParam", "gh_bool", "1", "false"),
            _ItemRule("UsingStandardOutputParam", "gh_bool", "1"),
        ),
        "Container",
        has_chunks=True,
    )
    using_standard_output = next(
        item.text == "true"
        for item in items
        if item.get("name") == "UsingStandardOutputParam"
    )
    attributes, parameters, script, editor = _expect_chunks(
        chunk,
        (
            ("Attributes", None),
            ("ParameterData", None),
            ("Script", None),
            ("ScriptEditor", None),
        ),
        "Container",
    )
    input_count, output_count, input_width, output_width = _validate_parameter_data(
        parameters,
        using_standard_output=using_standard_output,
    )
    component_height = (
        max(input_count, output_count, 1) * PARAMETER_ROW_HEIGHT
        + 2 * COMPONENT_EDGE_PADDING
    )
    component_width = (
        2 * COMPONENT_EDGE_PADDING
        + input_width
        + COMPONENT_CENTRE_BAND
        + output_width
    )
    _validate_attributes(
        attributes,
        expected_width=format(component_width, ".15g"),
        expected_height=format(component_height, ".15g"),
    )
    _validate_script(script)
    _validate_script_editor(editor)


def _validate_parameter_data(
    chunk: ET.Element,
    *,
    using_standard_output: bool,
) -> tuple[int, int, float, float]:
    items = _item_elements(chunk, "ParameterData", has_chunks=True)
    allowed_names = {"InputCount", "InputId", "OutputCount", "OutputId"}
    _reject_unexpected_item_names(items, allowed_names, "ParameterData")
    input_ids = [item for item in items if item.get("name") == "InputId"]
    output_ids = [item for item in items if item.get("name") == "OutputId"]
    rules = (
        _ItemRule("InputCount", "gh_int32", "3"),
        *(
            _ItemRule("InputId", "gh_guid", "9", index=index)
            for index in range(len(input_ids))
        ),
        _ItemRule("OutputCount", "gh_int32", "3"),
        *(
            _ItemRule("OutputId", "gh_guid", "9", index=index)
            for index in range(len(output_ids))
        ),
    )
    _validate_item_rules(items, rules, "ParameterData")

    parameters = _chunk_elements(chunk, "ParameterData")
    unexpected = next(
        (item for item in parameters if item.get("name") not in {"InputParam", "OutputParam"}),
        None,
    )
    if unexpected is not None:
        raise ArchiveSchemaError(
            "ParameterData has unexpected chunk "
            f"{unexpected.get('name')!r} outside the generated schema"
        )
    inputs = [item for item in parameters if item.get("name") == "InputParam"]
    outputs = [item for item in parameters if item.get("name") == "OutputParam"]
    expected = (
        *(("InputParam", index) for index in range(len(inputs))),
        *(("OutputParam", index) for index in range(len(outputs))),
    )
    ordered = _expect_chunks(chunk, expected, "ParameterData")
    input_chunks = ordered[: len(inputs)]
    output_chunks = ordered[len(inputs) :]
    input_width = _column_width(input_chunks, MIN_INPUT_WIDTH, "InputParam")
    output_width = _column_width(output_chunks, MIN_OUTPUT_WIDTH, "OutputParam")
    for parameter in input_chunks:
        _validate_user_parameter(parameter, is_input=True, width=input_width)
    standard = output_chunks and _is_standard_output(output_chunks[0])
    if bool(standard) != using_standard_output:
        raise ArchiveSchemaError(
            "UsingStandardOutputParam does not match the generated standard out parameter"
        )
    if standard:
        _validate_standard_output(output_chunks[0], width=output_width)
    for parameter in output_chunks[1 if standard else 0 :]:
        _validate_user_parameter(parameter, is_input=False, width=output_width)
    return len(input_chunks), len(output_chunks), input_width, output_width


def _is_standard_output(chunk: ET.Element) -> bool:
    """Report whether an output parameter is the component standard output."""

    items = chunk.find("./items")
    if items is None:
        return False
    return any(
        item.get("name") == "Name" and (item.text or "") == "out" for item in items
    )


def _column_width(chunks: list[ET.Element], minimum: float, context: str) -> float:
    """Return and validate the exact width generated from column labels."""

    widths: set[str] = set()
    for chunk in chunks:
        bounds = chunk.find("./chunks/chunk[@name='Attributes']/items/item[@name='Bounds']")
        if bounds is None:
            raise ArchiveSchemaError(f"{context} is missing canonical Attributes Bounds")
        width = bounds.find("./W")
        if width is None:
            raise ArchiveSchemaError(f"{context} Bounds is missing W")
        widths.add(width.text or "")
    if not widths:
        return minimum
    if len(widths) > 1:
        raise ArchiveSchemaError(f"{context} parameters must share one column width")
    value = widths.pop()
    _validate_canonical_number(value, f"{context} Bounds W")
    measured = float(value)
    if measured < minimum:
        raise ArchiveSchemaError(f"{context} column is narrower than the generated minimum")
    labels = []
    for chunk in chunks:
        nickname = chunk.find("./items/item[@name='NickName']")
        if nickname is None:
            raise ArchiveSchemaError(f"{context} is missing NickName")
        labels.append(nickname.text or "")
    longest = max((len(label) for label in labels), default=0)
    expected = min(
        MAX_COLUMN_WIDTH,
        max(minimum, longest * LABEL_CHARACTER_WIDTH + LABEL_PADDING),
    )
    if measured != expected:
        raise ArchiveSchemaError(
            f"{context} column width does not match its generated labels"
        )
    return measured


def _validate_user_parameter(chunk: ET.Element, *, is_input: bool, width: float) -> None:
    context = "InputParam" if is_input else "OutputParam"
    items = _item_elements(chunk, context, has_chunks=True)
    allowed_names = {
        "AllowTreeAccess",
        "Description",
        "InstanceGuid",
        "Name",
        "NickName",
        "Optional",
        "ScriptParamAccess",
        "ScriptParameterVersion",
        "ShowTypeHints",
        "Source",
        "SourceCount",
        "ToolTip",
        "TypeHintID",
    }
    _reject_unexpected_item_names(items, allowed_names, context)
    hint_count = sum(item.get("name") == "TypeHintID" for item in items)
    if hint_count > 1:
        raise ArchiveSchemaError(
            f"{context} TypeHintID must appear at most one time; found {hint_count}"
        )
    rules = (
        _ItemRule("AllowTreeAccess", "gh_bool", "1", "true" if is_input else "false"),
        _ItemRule(
            "Description",
            "gh_string",
            "10",
            max_length=MAX_DESCRIPTION_LENGTH,
            trimmed=True,
        ),
        _ItemRule("InstanceGuid", "gh_guid", "9"),
        _ItemRule(
            "Name",
            "gh_string",
            "10",
            max_length=MAX_NAME_LENGTH,
            allow_empty=False,
            trimmed=True,
        ),
        _ItemRule(
            "NickName",
            "gh_string",
            "10",
            max_length=MAX_NAME_LENGTH,
            trimmed=True,
        ),
        _ItemRule("Optional", "gh_bool", "1"),
        _ItemRule("ScriptParamAccess", "gh_int32", "3"),
        _ItemRule("ScriptParameterVersion", "gh_int32", "3", "2"),
        _ItemRule("ShowTypeHints", "gh_bool", "1"),
        *_source_rules(items, context),
        _ItemRule(
            "ToolTip",
            "gh_string",
            "10",
            max_length=MAX_DESCRIPTION_LENGTH,
            trimmed=True,
        ),
        *((_ItemRule("TypeHintID", "gh_guid", "9"),) if hint_count else ()),
    )
    _validate_item_rules(items, rules, context)

    chunks = _chunk_elements(chunk, context)
    converter_count = sum(item.get("name") == "ConverterData" for item in chunks)
    expected = (("Attributes", None),) + (
        (("ConverterData", None),) if converter_count else ()
    )
    ordered = _expect_chunks(chunk, expected, context)
    _validate_attributes(
        ordered[0],
        expected_width=format(width, ".15g"),
        expected_height="20",
    )
    if converter_count:
        if converter_count > 1:
            raise ArchiveSchemaError(
                f"{context} ConverterData must appear at most one time; found {converter_count}"
            )
        _validate_converter_data(ordered[1])


def _validate_standard_output(chunk: ET.Element, *, width: float) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule(
                "Description",
                "gh_string",
                "10",
                "Standard output and errors collected during the script run",
            ),
            _ItemRule("InstanceGuid", "gh_guid", "9"),
            _ItemRule("Name", "gh_string", "10", "out"),
            _ItemRule("NickName", "gh_string", "10", "out"),
            _ItemRule("Optional", "gh_bool", "1", "false"),
            _ItemRule("SourceCount", "gh_int32", "3", "0"),
        ),
        "standard OutputParam",
        has_chunks=True,
    )
    attributes = _expect_chunks(chunk, (("Attributes", None),), "standard OutputParam")[0]
    _validate_attributes(
        attributes,
        expected_width=format(width, ".15g"),
        expected_height="20",
    )


def _validate_attributes(
    chunk: ET.Element,
    *,
    expected_width: object = _ANY,
    expected_height: object = _ANY,
    minimum_height: float | None = None,
    context: str = "Attributes",
) -> None:
    bounds, pivot, _selected = _expect_items(
        chunk,
        (
            _ItemRule(
                "Bounds",
                "gh_drawing_rectanglef",
                "35",
                children=(
                    ("X", _ANY),
                    ("Y", _ANY),
                    ("W", expected_width),
                    ("H", expected_height),
                ),
            ),
            _ItemRule(
                "Pivot",
                "gh_drawing_pointf",
                "31",
                children=(("X", _ANY), ("Y", _ANY)),
            ),
            _ItemRule("Selected", "gh_bool", "1", "true"),
        ),
        "Attributes",
    )
    bounds_values = {child.tag: float(child.text or "") for child in bounds}
    if minimum_height is not None and bounds_values["H"] < minimum_height:
        raise ArchiveSchemaError(
            f"{context} height is smaller than the generated minimum"
        )
    pivot_values = {child.tag: child.text or "" for child in pivot}
    expected_pivot = {
        "X": format(bounds_values["X"] + bounds_values["W"] / 2.0, ".15g"),
        "Y": format(bounds_values["Y"] + bounds_values["H"] / 2.0, ".15g"),
    }
    if pivot_values != expected_pivot:
        raise ArchiveSchemaError("Attributes Pivot must match the center of Bounds")


def _validate_converter_data(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule("AssemblyName", "gh_string", "10"),
            _ItemRule("TypeName", "gh_string", "10"),
        ),
        "ConverterData",
    )


def _validate_script(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule("MarshGuids", "gh_bool", "1", "true"),
            _ItemRule("MarshInputs", "gh_bool", "1", "true"),
            _ItemRule("MarshOutputs", "gh_bool", "1", "true"),
            _ItemRule("Text", "gh_string", "10"),
            _ItemRule(
                "Title",
                "gh_string",
                "10",
                max_length=MAX_NAME_LENGTH,
                allow_empty=False,
                trimmed=True,
            ),
        ),
        "Script",
        has_chunks=True,
    )
    language = _expect_chunks(chunk, (("LanguageSpec", None),), "Script")[0]
    _expect_items(
        language,
        (
            _ItemRule("Taxon", "gh_string", "10", "*.*.python"),
            _ItemRule("Version", "gh_string", "10", "3.*"),
        ),
        "language specification",
    )


def _validate_script_editor(chunk: ET.Element) -> None:
    _expect_items(
        chunk,
        (
            _ItemRule(
                "StartBounds",
                "gh_drawing_rectangle",
                "34",
                children=(("X", "100"), ("Y", "100"), ("W", "700"), ("H", "700")),
            ),
        ),
        "ScriptEditor",
    )


def _expect_items(
    parent: ET.Element,
    rules: tuple[_ItemRule, ...],
    context: str,
    *,
    has_chunks: bool = False,
) -> list[ET.Element]:
    items = _item_elements(parent, context, has_chunks=has_chunks)
    _reject_unexpected_item_names(items, {rule.name for rule in rules}, context)
    _validate_item_rules(items, rules, context)
    return items


def _item_elements(
    parent: ET.Element,
    context: str,
    *,
    has_chunks: bool = False,
) -> list[ET.Element]:
    _reject_structural_text(parent, context)
    expected_tags = ["items", "chunks"] if has_chunks else ["items"]
    actual_tags = [child.tag for child in parent]
    if actual_tags != expected_tags:
        raise ArchiveSchemaError(
            f"{context} child elements are outside the canonical generated schema"
        )
    wrapper = parent[0]
    _expect_count_wrapper(wrapper, "items", context)
    _reject_structural_text(wrapper, f"{context} items")
    elements = list(wrapper)
    if any(element.tag != "item" for element in elements):
        raise ArchiveSchemaError(
            f"{context} contains an unexpected tag outside the generated schema"
        )
    return elements


def _chunk_elements(parent: ET.Element, context: str) -> list[ET.Element]:
    chunks = parent.find("./chunks")
    if chunks is None:
        raise ArchiveSchemaError(f"{context} is missing canonical chunks")
    _expect_count_wrapper(chunks, "chunks", context)
    _reject_structural_text(chunks, f"{context} chunks")
    elements = list(chunks)
    if any(element.tag != "chunk" for element in elements):
        raise ArchiveSchemaError(
            f"{context} contains an unexpected tag outside the generated schema"
        )
    return elements


def _expect_chunks(
    parent: ET.Element,
    expected: tuple[tuple[str, int | None], ...],
    context: str,
) -> list[ET.Element]:
    elements = _chunk_elements(parent, context)
    expected_names = [name for name, _index in expected]
    actual_names = [element.get("name") for element in elements]
    for name in set(expected_names):
        expected_count = expected_names.count(name)
        actual_count = actual_names.count(name)
        if expected_count == 1 and actual_count != 1:
            if actual_count == 0:
                raise ArchiveSchemaError(f"{context} is missing {name}")
            raise ArchiveSchemaError(
                f"{context} {name} must appear exactly one time; found {actual_count}"
            )
    unexpected = next((name for name in actual_names if name not in expected_names), None)
    if unexpected is not None:
        raise ArchiveSchemaError(
            f"{context} has unexpected chunk {unexpected!r} outside the generated schema"
        )
    if actual_names != expected_names:
        raise ArchiveSchemaError(f"{context} chunks are not in canonical generated order")
    for element, (name, index) in zip(elements, expected, strict=True):
        attributes = {"name": name}
        if index is not None:
            attributes["index"] = str(index)
        _expect_attributes(element, attributes, f"{context} {name}")
    return elements


def _validate_item_rules(
    elements: list[ET.Element],
    rules: tuple[_ItemRule, ...],
    context: str,
) -> None:
    expected_names = [rule.name for rule in rules]
    actual_names = [element.get("name") for element in elements]
    for name in set(expected_names):
        expected_count = expected_names.count(name)
        actual_count = actual_names.count(name)
        if expected_count == 1 and actual_count != 1:
            if actual_count == 0:
                raise ArchiveSchemaError(f"{context} is missing {name}")
            raise ArchiveSchemaError(
                f"{context} {name} must appear exactly one time; found {actual_count}"
            )
    if actual_names != expected_names:
        raise ArchiveSchemaError(f"{context} items are not in canonical generated order")
    for element, rule in zip(elements, rules, strict=True):
        attributes = {
            "name": rule.name,
            "type_name": rule.type_name,
            "type_code": rule.type_code,
        }
        if rule.index is not None:
            attributes["index"] = str(rule.index)
        _expect_attributes(element, attributes, f"{context} {rule.name}")
        _validate_item_content(element, rule, context)


def _validate_item_content(element: ET.Element, rule: _ItemRule, context: str) -> None:
    children = list(element)
    expected_child_names = [name for name, _value in rule.children]
    if children and element.text and element.text.strip():
        raise ArchiveSchemaError(
            f"{context} {rule.name} contains unexpected structural text"
        )
    if [child.tag for child in children] != expected_child_names:
        raise ArchiveSchemaError(
            f"{context} {rule.name} child elements are outside the canonical generated schema"
        )
    for child, (name, expected_value) in zip(children, rule.children, strict=True):
        _expect_attributes(child, {}, f"{context} {rule.name} {name}")
        if list(child):
            raise ArchiveSchemaError(
                f"{context} {rule.name} {name} contains an unexpected generated-schema child"
            )
        if child.tail and child.tail.strip():
            raise ArchiveSchemaError(
                f"{context} {rule.name} contains unexpected structural text"
            )
        if expected_value is not _ANY and (child.text or "") != expected_value:
            raise ArchiveSchemaError(f"{context} {rule.name} {name} is not canonical")
        if expected_value is _ANY:
            _validate_canonical_number(child.text or "", f"{context} {rule.name} {name}")
    if rule.type_name == "gh_guid":
        try:
            identifier = UUID(element.text or "")
        except ValueError as error:
            raise ArchiveSchemaError(
                f"{context} {rule.name} must be a valid UUID"
            ) from error
        if str(identifier) != (element.text or ""):
            raise ArchiveSchemaError(
                f"{context} {rule.name} must use canonical UUID text"
            )
    if rule.type_name == "gh_string" and rule.name != "Text":
        value = element.text or ""
        if contains_unsafe_terminal_text(value):
            if any(
                ord(character) < 0x20 or 0x7F <= ord(character) < 0xA0
                for character in value
            ):
                raise ArchiveSchemaError(
                    f"{context} {rule.name} contains a terminal control character"
                )
            raise ArchiveSchemaError(
                f"{context} {rule.name} contains an unsafe terminal formatting character"
            )
        if not rule.allow_empty and not value:
            raise ArchiveSchemaError(f"{context} {rule.name} must be non-empty")
        if rule.max_length is not None and len(value) > rule.max_length:
            raise ArchiveSchemaError(
                f"{context} {rule.name} must contain at most {rule.max_length} characters"
            )
        if rule.trimmed and value != value.strip():
            raise ArchiveSchemaError(
                f"{context} {rule.name} must not start or end with whitespace"
            )
    if rule.value is not _ANY and (element.text or "") != rule.value:
        raise ArchiveSchemaError(f"{context} {rule.name} is not canonical")


def _reject_unexpected_item_names(
    elements: list[ET.Element],
    allowed: set[str],
    context: str,
) -> None:
    unexpected = next(
        (element.get("name") for element in elements if element.get("name") not in allowed),
        None,
    )
    if unexpected is not None:
        raise ArchiveSchemaError(
            f"{context} has unexpected item {unexpected!r} outside the generated schema"
        )


def _expect_count_wrapper(element: ET.Element, tag: str, context: str) -> None:
    if element.tag != tag or set(element.attrib) != {"count"}:
        raise ArchiveSchemaError(f"{context} {tag} attributes are not canonical")


def _expect_attributes(element: ET.Element, expected: dict[str, str], context: str) -> None:
    if element.attrib != expected:
        if "index" in expected and element.get("index") != expected["index"]:
            raise ArchiveSchemaError(f"{context} index is not canonical")
        raise ArchiveSchemaError(f"{context} attributes are not canonical")


def _reject_structural_text(element: ET.Element, context: str) -> None:
    if element.text and element.text.strip():
        raise ArchiveSchemaError(f"{context} contains unexpected structural text")
    for child in element:
        if child.tail and child.tail.strip():
            raise ArchiveSchemaError(f"{context} contains unexpected structural text")


def _validate_canonical_number(value: str, context: str) -> None:
    try:
        number = float(value)
    except ValueError as error:
        raise ArchiveSchemaError(f"{context} must be a canonical numeric coordinate") from error
    if not math.isfinite(number) or format(number, ".15g") != value:
        raise ArchiveSchemaError(f"{context} must be a canonical numeric coordinate")
