from __future__ import annotations

import base64
import hashlib
import json
import runpy
import shutil
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

from ghravioli.build import build_bytes
from ghravioli.identity import SequenceIdentityProvider
from ghravioli.manifest import load_manifest
from ghravioli.model import ComponentManifest, GraphManifest


class ExamplesTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.repo_root = Path(__file__).resolve().parents[1]
        cls.examples = cls.repo_root / "examples"

    def test_every_example_manifest_validates_and_builds(self) -> None:
        manifests = sorted(self.examples.rglob("*.toml"))
        self.assertGreaterEqual(len(manifests), 3)

        for path in manifests:
            with self.subTest(path=path):
                manifest = load_manifest(path)
                archive = build_bytes(path, identities=SequenceIdentityProvider())
                root = ET.fromstring(archive)
                object_count = int(root.findtext(".//chunk[@name='DefinitionObjects']/items/item[@name='ObjectCount']", "0"))
                objects = root.findall(".//chunk[@name='DefinitionObjects']/chunks/chunk[@name='Object']")
                self.assertEqual(object_count, len(objects))
                scripts = [
                    chunk
                    for chunk in objects
                    if chunk.findtext("./items/item[@name='Name']") == "Python 3 Script"
                ]
                expected_count = 1 if isinstance(manifest, ComponentManifest) else len(manifest.components)
                self.assertEqual(len(scripts), expected_count)
                # Companions are placed alongside, never instead of, a component.
                self.assertGreater(len(objects), len(scripts))

    def test_embedded_example_source_round_trips_exactly(self) -> None:
        for path in sorted(self.examples.rglob("component.toml")):
            with self.subTest(path=path):
                manifest = load_manifest(path)
                assert isinstance(manifest, ComponentManifest)
                archive = build_bytes(path, identities=SequenceIdentityProvider())
                root = ET.fromstring(archive)
                encoded = root.findtext(".//chunk[@name='Script']/items/item[@name='Text']")
                self.assertIsNotNone(encoded)
                self.assertEqual(base64.b64decode(encoded or "").decode("utf-8"), manifest.source_text)

    def test_default_examples_preserve_pre_panel_archive_bytes(self) -> None:
        # Deterministic archives generated by main at da31bf2, before output panels.
        historical_hashes = {
            "scale_points/component.toml": (
                "93e3cac4c94a23fa25f9abc2f9260aa1fc1c843262a2aaab5beb557b50f6e9e3",
                "d1b6a694fdd3a13b778ee28a17064267cf8594ac47429de5e6d02b818bc867da",
            ),
            "json_config/component.toml": (
                "14cddb7abebf1c0c4871d87662df3ec716e628927ef1ff661cfcc65d08ba2f9f",
                "7c52efe622bd287d85e31fdeb8c306d4d5b2fd194683659c79cb88ccbde1de02",
            ),
            "pipeline.toml": (
                "1f79cd18f7dbe1bbd7d17559ad929fb63face2fbf5ce0638851265af3a5328c9",
                "06d065aa0a4742af40c57237b14cb281805ea713e55d7c12d34577eb13120fdc",
            ),
        }
        # Git may check out CRLF on Windows. Embedded source preserves its exact
        # bytes, so exercise both line endings explicitly on every platform.
        for index, newline in enumerate(("\n", "\r\n")):
            with tempfile.TemporaryDirectory() as folder:
                examples = Path(folder) / "examples"
                shutil.copytree(self.examples, examples)
                for source in examples.rglob("*.py"):
                    text = source.read_text(encoding="utf-8")
                    source.write_bytes(text.replace("\n", newline).encode("utf-8"))
                for relative, expected in historical_hashes.items():
                    with self.subTest(manifest=relative, newline=newline):
                        archive = build_bytes(examples / relative, identities=SequenceIdentityProvider())
                        self.assertEqual(hashlib.sha256(archive).hexdigest(), expected[index])

    def test_native_geometry_example_keeps_values_native(self) -> None:
        namespace = runpy.run_path(
            str(self.examples / "scale_points" / "component.py"),
            init_globals={"points": [2, 3], "factor": 2.0},
        )

        self.assertEqual(namespace["scaled_points"], [4.0, 6.0])
        self.assertIsInstance(namespace["scaled_points"], list)
        self.assertIn("scaled 2 point", namespace["log"])

    def test_json_example_outputs_a_versioned_string_envelope(self) -> None:
        namespace = runpy.run_path(
            str(self.examples / "json_config" / "component.py"),
            init_globals={"label": "study", "count": 3.0},
        )

        self.assertIsInstance(namespace["config"], str)
        envelope = json.loads(namespace["config"])
        self.assertEqual(
            set(envelope),
            {"schema", "version", "producer", "payload", "warnings"},
        )
        self.assertEqual(envelope["schema"], "example.config")
        self.assertEqual(envelope["version"], 1)
        self.assertEqual(envelope["payload"], {"label": "study", "count": 3})
        self.assertIsInstance(namespace["log"], str)

    def test_pipeline_is_a_placed_graph_without_connections(self) -> None:
        graph = load_manifest(self.examples / "pipeline.toml")
        self.assertIsInstance(graph, GraphManifest)
        assert isinstance(graph, GraphManifest)
        self.assertEqual(len(graph.components), 2)
        self.assertNotIn("connections", (self.examples / "pipeline.toml").read_text(encoding="utf-8"))

    def test_templates_and_examples_do_not_mask_programming_errors(self) -> None:
        sources = [
            self.repo_root / "templates" / "component" / "component.py",
            *sorted(self.examples.rglob("component.py")),
        ]
        for source in sources:
            with self.subTest(source=source):
                text = source.read_text(encoding="utf-8")
                self.assertNotIn("except Exception", text)
                self.assertIn("except (TypeError, ValueError)", text)


if __name__ == "__main__":
    unittest.main()
